In [1]:
%matplotlib inline
import os
import pandas as pd
import numpy as np

## Get data

In [2]:
df = pd.read_csv('speeches.csv')
df

Filename          State       Governor  Gender Party  \
0     Alabama_Inaugural.txt        Alabama       Kay Ivey  Female     R   
1          Alabama_SOTS.txt        Alabama       Kay Ivey  Female     R   
2                       NaN         Alaska  Mike Dunleavy    Male     R   
3           Alaska_SOTS.txt         Alaska  Mike Dunleavy    Male     R   
4     Arizona_Inaugural.txt        Arizona     Doug Ducey    Male     R   
..                      ...            ...            ...     ...   ...   
76    WestVirginia_SOTS.txt  West Virginia    Jim Justice    Male     R   
77  Wisconsin_Inaugural.txt      Wisconsin     Tony Evers    Male     D   
78       Wisconsin_SOTS.txt      Wisconsin     Tony Evers    Male     D   
79    Wyoming_Inaugural.txt        Wyoming    Mark Gordon    Male     R   
80         Wyoming_SOTS.txt        Wyoming    Mark Gordon    Male     R   

        Type of Speech New Gov? 2020 Contender?   Region     Trifecta Status  \
0            Inaugural       No              No    South          R trifecta   
1   State of the state       No              No    South          R trifecta   
2            Inaugural      Yes              No     West  Divided government   
3   State of the state      Yes              No     West  Divided government   
4            Inaugural       No              No     West          R trifecta   
..                 ...      ...             ...      ...                 ...   
76  State of the state       No              No    South          R trifecta   
77           Inaugural      Yes              No  Midwest  Divided government   
78  State of the state      Yes              No  Midwest  Divided government   
79           Inaugural      Yes              No     West          R trifecta   
80  State of the state      Yes              No     West          R trifecta   

    Trifecta                                Best Transcript URL Selector Note  \
0   Trifecta  https://governor.alabama.gov/remarks-speeches/...      NaN  NaN   
1   Trifecta  https://governor.alabama.gov/remarks-speeches/...      NaN  NaN   
2    Divided                            No transcript available      NaN  NaN   
3    Divided  https://gov.alaska.gov/newsroom/2019/01/22/201...      NaN  NaN   
4   Trifecta  https://azgovernor.gov/governor/news/2019/01/g...      NaN  NaN   
..       ...                                                ...      ...  ...   
76  Trifecta  https://governor.wv.gov/News/press-releases/20...      NaN  NaN   
77   Divided  https://evers.wi.gov/Pages/Newsroom/Press-Rele...      NaN  NaN   
78   Divided  https://evers.wi.gov/Pages/Newsroom/Press-Rele...      NaN  NaN   
79  Trifecta  https://governor.wyo.gov/media/news-releases/g...      NaN  NaN   
80  Trifecta  https://drive.google.com/file/d/0B5QDlu63DmCiY...      NaN  NaN   

                                Lesser Transcript URL  \
0   https://www.al.com/news/2019/01/the-full-text-...   
1                                                 NaN   
2                                                 NaN   
3   https://www.adn.com/politics/2019/01/23/watch-...   
4                                                 NaN   
..                                                ...   
76                                                NaN   
77  https://www.wisn.com/article/read-gov-evers-in...   
78  https://www.wbay.com/content/news/Evers-to-emp...   
79  http://kgab.com/gov-mark-gordons-inauguration-...   
80                                                NaN   

                              New Best Transcript URL  
0                                                 NaN  
1   https://governor.alabama.gov/remarks-speeches/...  
2                                                 NaN  
3   https://gov.alaska.gov/newsroom/2019/01/22/201...  
4                                                 NaN  
..                                                ...  
76  https://governor.wv.gov/News/press-releases/20...  
77                                                N

In [3]:
# Ensure 'Filename' is not 'N/A' and not NaN
df = df[(df['Filename'] != 'N/A') & (df['Filename'].notna())]

# Using .loc to ensure we are modifying the DataFrame safely
df.loc[:, 'filepath'] = 'speeches/' + df['Filename']
df.loc[:, 'file_exists'] = df['filepath'].apply(lambda x: os.path.isfile(x))

# Display the first few rows of the DataFrame
df.head()


/var/folders/k2/wlk_zlxn02sb9f62n1gwmpw00000gn/T/ipykernel_34728/2747375272.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'filepath'] = 'speeches/' + df['Filename']
/var/folders/k2/wlk_zlxn02sb9f62n1gwmpw00000gn/T/ipykernel_34728/2747375272.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'file_exists'] = df['filepath'].apply(lambda x: os.path.isfile(x))


Filename    State       Governor  Gender Party  \
0  Alabama_Inaugural.txt  Alabama       Kay Ivey  Female     R   
1       Alabama_SOTS.txt  Alabama       Kay Ivey  Female     R   
3        Alaska_SOTS.txt   Alaska  Mike Dunleavy    Male     R   
4  Arizona_Inaugural.txt  Arizona     Doug Ducey    Male     R   
5       Arizona_SOTS.txt  Arizona     Doug Ducey    Male     R   

       Type of Speech New Gov? 2020 Contender? Region     Trifecta Status  \
0           Inaugural       No              No  South          R trifecta   
1  State of the state       No              No  South          R trifecta   
3  State of the state      Yes              No   West  Divided government   
4           Inaugural       No              No   West          R trifecta   
5  State of the state       No              No   West          R trifecta   

   Trifecta                                Best Transcript URL Selector Note  \
0  Trifecta  https://governor.alabama.gov/remarks-speeches/...      NaN  NaN   
1  Trifecta  https://governor.alabama.gov/remarks-speeches/...      NaN  NaN   
3   Divided  https://gov.alaska.gov/newsroom/2019/01/22/201...      NaN  NaN   
4  Trifecta  https://azgovernor.gov/governor/news/2019/01/g...      NaN  NaN   
5  Trifecta  https://azgovernor.gov/governor/news/2019/01/g...      NaN  NaN   

                               Lesser Transcript URL  \
0  https://www.al.com/news/2019/01/the-full-text-...   
1                                                NaN   
3  https://www.adn.com/politics/2019/01/23/watch-...   
4                                                NaN   
5                                                NaN   

                             New Best Transcript URL  \
0                                                NaN   
1  https://governor.alabama.gov/remarks-speeches/...   
3  https://gov.alaska.gov/newsroom/2019/01/22/201...   
4                                                NaN   
5  https://azgovernor.gov/governor/news/2019/01/g...   

                         filepath  file_exists  
0  speeches/Alabama_Inaugural.txt         True  
1       speeches/Alabama_SOTS.txt         True  
3        speeches/Alaska_SOTS.txt         True  
4  speeches/Arizona_Inaugural.txt         True  
5       speeches/Arizona_SOTS.txt         True

## Filter Data

In [4]:
df = df[df['Type of Speech'].isin(['State of the state','Both'])]
f"Dataset is {len(df)} speeches"

'Dataset is 50 speeches'

## Read Speeches

In [5]:
def get_speeches(df):
    speeches = []
    for path in df['filepath']:
        with open(path) as f:
            text = f.read()
            speeches.append(text)
    return speeches

speeches = get_speeches(df)

## Turn Speeches Into Vectors!

In [6]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

## YOU CAN EDIT THESE
y_columns = ['Party', 'Trifecta']
BINARY=True
NGRAMS=(1,1)
MIN_DF=0.0

def ngram_vectorizer(n, binary, min_df):
    return TfidfVectorizer(
        stop_words='english', # 'english' if not custom list
        ngram_range=NGRAMS,
        binary=binary,
        min_df=min_df
    )


In [7]:
vectorizer = ngram_vectorizer(NGRAMS, binary=BINARY, min_df=MIN_DF)
X = vectorizer.fit_transform(speeches)
y = np.array(df['Party'])

In [8]:
# showing you the array!
print(X.shape)
X.toarray()

(50, 11344)


array([[0.        , 0.01488516, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.0152703 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.0131105 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.04604435, 0.01246666, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.01709833, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [9]:
# turning it back into a dataframe for visibility
word_vectors = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
df[['State', 'Governor', 'Party', 'Trifecta Status']].reset_index().\
    merge(word_vectors, left_index=True, right_index=True).head()

index_x       State        Governor Party     Trifecta Status   00  \
0        1     Alabama        Kay Ivey     R          R trifecta  0.0   
1        3      Alaska   Mike Dunleavy     R  Divided government  0.0   
2        5     Arizona      Doug Ducey     R          R trifecta  0.0   
3        6    Arkansas  Asa Hutchinson     R          R trifecta  0.0   
4        9  California    Gavin Newsom     D          D trifecta  0.0   

        000  000th  028  043  ...  zero  zinke  zip  zoey       zoi  zone  \
0  0.014885    0.0  0.0  0.0  ...   0.0    0.0  0.0   0.0  0.000000   0.0   
1  0.015270    0.0  0.0  0.0  ...   0.0    0.0  0.0   0.0  0.056399   0.0   
2  0.013110    0.0  0.0  0.0  ...   0.0    0.0  0.0   0.0  0.000000   0.0   
3  0.015701    0.0  0.0  0.0  ...   0.0    0.0  0.0   0.0  0.000000   0.0   
4  0.011937    0.0  0.0  0.0  ...   0.0    0.0  0.0   0.0  0.000000   0.0   

     zones   zoning  zoom  zoot  
0  0.00000  0.00000   0.0   0.0  
1  0.00000  0.00000   0.0   0.0  
2  0.00000  0.00000   0.0   0.0  
3  0.00000  0.00000   0.0   0.0  
4  0.02967  0.04409   0.0   0.0  

[5 rows x 11349 columns]

In [10]:
print(y)
y = (y == 'R').astype('int')
y

['R' 'R' 'R' 'R' 'D' 'D' 'D' 'D' 'R' 'R' 'D' 'R' 'D' 'R' 'R' 'D' 'R' 'D'
 'D' 'R' 'R' 'D' 'D' 'R' 'R' 'D' 'R' 'D' 'R' 'D' 'D' 'D' 'D' 'R' 'R' 'R'
 'D' 'D' 'D' 'R' 'R' 'R' 'R' 'R' 'R' 'D' 'D' 'R' 'D' 'R']


array([1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1])

## Train/Test Split

In [11]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3)


## Train a Classifier

In [12]:
# Import the classifier from scikit-learn
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

# define model
clf = LogisticRegression(C=1e9, solver='lbfgs', max_iter=4000) 
# clf = MultinomialNB(alpha=1.0e-10, class_prior=None, fit_prior=True)

# fit model on training data
clf.fit(X_train, y_train)


LogisticRegression(C=1000000000.0, max_iter=4000)

In [13]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y, clf.predict(X))
pd.DataFrame(matrix, 
             columns = ['pred_Dem', 'pred_Rep'], 
             index=['Dem', 'Rep'])\
    .assign(Total=lambda x: x.sum(axis=1))\
    .sort_values(by='Total')[['pred_Rep', 'pred_Dem', 'Total']]\
    .T.assign(Total = lambda x: x.sum(axis=1)).T


pred_Rep  pred_Dem  Total
Dem           6        17     23
Rep          27         0     27
Total        33        17     50

In [14]:
from sklearn.metrics import recall_score,accuracy_score, precision_score, f1_score

# accuracy is the proportion of correctly predicted labels out of all labels
print("accuracy_score", round(accuracy_score(y_test, clf.predict(X_test)),2))

# note: for precision and recall, we're interested in what 1 is (in this case, Republican)

# precision is the proportion of correctly predicted Republicans out of all predicted Republicans
print("precision_score", precision_score(y_test, clf.predict(X_test)).round(2))
# recall is the proportion of correctly predicted Republicans out of all actual Republicans
print("recall_score", recall_score(y_test, clf.predict(X_test)).round(2))
# f1 score is the harmonic mean of precision and recall
print("f1_score", f1_score(y_test, clf.predict(X_test)).round(2))


accuracy_score 0.6
precision_score 0.57
recall_score 1.0
f1_score 0.73


##  Cross Validation

In [15]:
from sklearn.model_selection import cross_val_score, cross_validate

In [16]:
# 5-fold cross-validation
scoring = ['accuracy', 'precision', 'recall', 'f1']
scores = cross_validate(clf, X, y, scoring=scoring, cv=4)
pd.DataFrame(scores).round(2)

fit_time  score_time  test_accuracy  test_precision  test_recall  test_f1
0      0.02         0.0           0.62            0.58         1.00     0.74
1      0.01         0.0           0.54            0.55         0.86     0.67
2      0.01         0.0           0.83            0.78         1.00     0.88
3      0.01         0.0           0.75            0.67         1.00     0.80

In [17]:
cross_val_score(clf, X, y)

array([0.7, 0.6, 0.6, 0.8, 0.7])

## Make a prediction

In [18]:
new_speeches = [
    "I support gun control, a higher minimum wage, and universal healthcare.",
    "I support lower taxes, less government, and a strong military."
]


In [19]:
speech_vector = vectorizer.transform(new_speeches)

In [20]:
speech_vector

<2x11344 sparse matrix of type '<class 'numpy.float64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [21]:
clf.predict(speech_vector)

array([0, 1])

In [22]:
clf.predict_proba(speech_vector)

array([[0.69535384, 0.30464616],
       [0.20499373, 0.79500627]])

## The Piece
https://fivethirtyeight.com/features/what-americas-governors-are-talking-about/